defaults: &defaults
  working_directory: ~/challenge
  docker:
    - image: circleci/node:10.10.0-stretch-browsers-legacy
    - image: circleci/postgres:9.6.5-alpine-ram
      environment:
          POSTGRES_USER: root
          POSTGRES_DB: testing
version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: execute build script
          command: docker build . -t test_runner
      - run:
          name: Run tests
          command: |
              set -x
              docker run -it test_runner script/api_tests.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
         filters:
            branches:
              only:
                - develop
                - qa
                - stage
                - master

